wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.8.5
      5: 0.10.22
      8:
      - 5
activation:
  desc: null
  value: Sigmoid
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: CrossEntropy
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: minimize
    name: loss
name:
  desc: null
  value: random-test-sweep
num_epochs:
  desc: null
  value: 10
optimizer:
  desc: null
  value: Nadam
parameters:
  desc: null
  value:
    activation:
      values:
      - Sigmoid
      - Tanh
      - Relu
    batch_size:
      values:
      - 128
      - 256
      - 512
      - 1024
      - 10000
      - 60000
    learning_rate:
      values:
      - 0.001
      - 0.0001
    loss:
      values:
      - CrossEntropy
      - SquaredError
    num_epochs:
      values:
      - 10
      - 50
      - 100
    optimizer:
      values:
      - Normal
      - Momentum
      - AdaGrad
      - RMSProp
      - Adam
      - Nadam
    size_hidden_layer:
      values:
      - 32
      - 64
      - 128
    weight_init:
      values:
      - RandomNormal
      - XavierUniform
size_hidden_layer:
  desc: null
  value: 32
weight_init:
  desc: null
  value: RandomNormal
