wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 128
learning_rate:
  value: 0.001
loss:
  value: CrossEntropy
num_epochs:
  value: 10
optimizer:
  value: Normal
size_hidden_layer:
  value: 128
weight_init:
  value: RandomNormal
