# -*- coding: utf-8 -*-
"""Assignment1-Q7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/184QFISt0c7J4EUEbEs8asTRXhHlF6PxJ
"""

import wandb
import numpy as np
import os
from activations import Sigmoid, Tanh, Relu, Softmax
from layers import Input, Dense
from optimizers import Momentum, Nesterov, AdaGrad, RMSProp, Adam, Nadam
from network import NeuralNetwork
from loss import CrossEntropy
from helper import OneHotEncoder, MinMaxScaler

from sklearn.model_selection import train_test_split

from keras.datasets import fashion_mnist
import matplotlib.pyplot as plt

# Loading and preprocessing the data
[(x_train, y_train), (x_test, y_test)] = fashion_mnist.load_data()
scaler = MinMaxScaler()
scaler.fit(x_train)
X_scaled = x_train/255
X_test_scaled = x_test/255

X_scaled = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1]*X_scaled.shape[2]).T
X_test_scaled = X_test_scaled.reshape(X_test_scaled.shape[0], X_test_scaled.shape[1]*X_test_scaled.shape[2]).T

encoder = OneHotEncoder()
t_train = encoder.fit_transform(y_train, 10)
t_test = encoder.fit_transform(y_test, 10)

layers = [Input(data = X_scaled), \
          Dense(size = 64, activation = 'Sigmoid', name= 'HL1'), \
          Dense(size = 10, activation = 'Sigmoid', name = 'OL')]

nn_model = NeuralNetwork(layers = layers, batch_size = 128, \
                         optimizer = 'RMSProp', intialization = 'XavierUniform', \
                         epochs = 50, t = t_train, X_val = X_test_scaled, t_val = t_test, loss = "CrossEntropy") 
nn_model.forward_propogation()
nn_model.backward_propogation()

_, _, ypred = nn_model.check_test(X_test_scaled, y_test)
y_labels_pred = np.argmax(ypred, axis = 0)

print('Accuracy on test set = {}'.format(np.sum(y_test == y_labels_pred)/y_test.shape[0]))

wandb.init(project = 'FDL-Q7-Run3')
wandb.log({"conf_mat" : wandb.plot.confusion_matrix(probs = None,\
                        y_true = y_test, preds = y_labels_pred, \
                        class_names = np.arange(10))})