wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 128
loss:
  value: CrossEntropy
num_epochs:
  value: 50
optimizer:
  value: AdaGrad
size_hidden_layer:
  value: 128
weight_init:
  value: XavierUniform
