wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 128
loss:
  value: SquaredError
num_epochs:
  value: 50
optimizer:
  value: RMSProp
size_hidden_layer:
  value: 64
weight_init:
  value: XavierUniform
