wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.8.5
      5: 0.10.22
      8:
      - 5
