wandb_version: 1

activation:
  value: Sigmoid
batch_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: CrossEntropy
num_epochs:
  value: 10
optimizer:
  value: Normal
weight_init:
  value: RandomNormal
