wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.8.5
      5: 0.10.22
      8:
      - 5
activation:
  desc: null
  value: Sigmoid
batch_size:
  desc: null
  value: 128
loss:
  desc: null
  value: SquaredError
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: minimize
    name: loss
name:
  desc: null
  value: best-sweep
num_epochs:
  desc: null
  value: 1
optimizer:
  desc: null
  value: RMSProp
parameters:
  desc: null
  value:
    activation:
      values:
      - Sigmoid
    batch_size:
      values:
      - 128
    loss:
      values:
      - SquaredError
    num_epochs:
      values:
      - 1
    optimizer:
      values:
      - RMSProp
    size_hidden_layer:
      values:
      - 64
    weight_init:
      values:
      - XavierUniform
size_hidden_layer:
  desc: null
  value: 64
weight_init:
  desc: null
  value: XavierUniform
